version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-master
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - jenkinsnet
    restart: always

volumes:
  jenkins-data:

networks:
  jenkinsnet:
